[project]
name = "comfyui_inteliweb_nodes"   # id único (no pongas "ComfyUI" en el nombre)
version = "0.13.0"
description = "System Check (Inteliweb): RAM/VRAM live, Free RAM/VRAM buttons, Flash-Attn check."
license = { text = "Apache-2.0" }
dependencies = []  # si no instalas nada por pip, déjalo vacío

[project.urls]
Repository = "https://github.com/maoper11/comfyui_inteliweb_nodes"

[tool.comfy]
PublisherId = "maoper11"          # tu Publisher de registry.comfy.org
DisplayName = "System Check (Inteliweb)"
Icon = ""
Banner = ""
Categories = ["Utility"]          # Categorías en comfyui.org
Tags = ["system", "check", "ram", "vram", "flash-attn", "inteliweb"]  # Etiquetas en comfyui.org
Models = []                       # Modelos que usa tu nodo, si no usa ninguno, déjalo vacío
